python -m torch.distributed.launch --nproc_per_node=2 --master_port=12233 --use_env run_train.py \
--diff_steps 2000 \
--lr 0.0001 \
--learning_steps 5001 \
--save_interval 100 \
--seed 123 \
--noise_schedule sqrt \
--hidden_dim 128 \
--bsz 512 \
--dataset ProtDebug \
--data_dir datasets/Conversation \
--vocab bert \
--seq_len 256 \
--schedule_sampler lossaware \
--notes debug
