python -m torch.distributed.launch --nproc_per_node=2 --master_port=12233 --use_env run_train.py \
--diff_steps 1000 \
--lr 0.0001 \
--learning_steps 3001 \
--save_interval 1000 \
--seed 102 \
--noise_schedule sqrt \
--hidden_dim 128 \
--dropout 0 \
--bsz 128 \
--dataset ProtMedium \
--data_dir datasets/ProtMediumCorrect \
--vocab protbert \
--seq_len 128 \
--schedule_sampler lossaware \
--notes pm-correct
