accelerate launch --multi_gpu run_train.py \
	--diff_steps 3000 \
	--lr 0.00001 \
	--learning_steps 1000001 \
	--save_interval 1000 \
	--seed 102 \
	--noise_schedule sqrt \
	--hidden_dim 1024 \
	--bsz 32 \
	--dataset ProtMinimal \
	--data_dir datasets/ProtMinimal \
	--vocab protbert \
	--seq_len 1024 \
	--schedule_sampler lossaware \
	--notes ProtMinimalDebugAccelerate
