python3 -m torch.distributed.launch --nproc_per_node=8 --master_port=12250 --use_env run_train.py \
--diff_steps 4000 \
--lr 0.0001 \
--learning_steps 20001 \
--save_interval 2000 \
--seed 102 \
--noise_schedule sqrt \
--hidden_dim 128 \
--bsz 256 \
--dataset ProtSmall \
--data_dir datasets/ProtMinimalStrucToSeq/ \
--vocab protbert \
--seq_len 256 \
--schedule_sampler lossaware \
--notes MinimalRunTestIfWorksWithSmallerModeResetParams
